version: "2"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 11000:8080
volumes:
  my_dbdata: